# Generated by Django 3.0.7 on 2020-06-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_topping_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
