# Generated by Django 3.0.7 on 2020-06-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20200619_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topping',
            new_name='Toppings',
        ),
    ]
